[project]
name = "tacozip"
version = "0.1.0"
requires-python = ">=3.9"
description = "Fast ZIP-like container with ghost metadata"
readme = "README.md"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["tacozip"]

[tool.setuptools.package-data]
tacozip = ["libtacozip*.so", "libtacozip*.dylib", "libtacozip*.dll", "tacozip.dll"]

#[tool.scikit-build]
#wheel.packages = ["clients/python"]
#editable.mode = "redirect"
#sdist.include = [
#  "CMakeLists.txt",
#  "src/**",
#  "include/**",
#  "cmake/**",
#  "clients/python/**",
#  "README.md",
#  "LICENSE",
#]

#[tool.scikit-build.cmake]
#source-dir = "../.."

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"